### ISSUE TITLE
Smaller level sizes cause FPS display and pause menu to become bigger

### ISSUE THREAD

**Issue by SkaillZ** [complementaries/complementary#103]
Caused by the scaling in tile map space

**Comment by SkaillZ** [comment]
also affects how far the cutscenes zoom in

**Comment by MisterSnuvi** [comment]
FPS display and menus are fixed

**Comment by MisterSnuvi** [comment]
Icon rendering stays fixed to level size for now to always take same space of levels and to not break the ability cutscene.
