### ISSUE TITLE
Particle simulation

### ISSUE THREAD

**Issue by SkaillZ** [complementaries/complementary#16]
- [x]  Lifetime (wie lange lebt ein einzelner Partikel)
- [x]   Velocity + Random offset (Vector)
- [x]      Gravity (Stärke als Float)
- [x]      Shape (gleichseitiges Dreieck, Kreis, Quadrat)
- [x]     Spawnrate + Duration (Gesamtdauer während Partikel gespawned werden)
- [x]      Position + Random offset (Vector)
- [x]      Start Color + End Color
- [x]      Start Size + End Size
- [ ]      (Start + End Rotation)
- [x]      Collision mit Tiles
  - [ ]          Aktivierbar und deaktivierbar
  - [ ]          Bounciness?
  - [ ]          Kill on impact?
- [ ]      (Subemitter)

**Comment by MisterSnuvi** [comment]
Particles can be spawned. They have:
- lifetime
- velocity
- gravity
- a start size
- an end size
- a start color
- an end color
The shape is a circle, a triangle or a square.
